---
name: apply
on:
  push:
    branches: [main]
env:
  TFACTION_IS_APPLY: "true"
jobs:
  setup:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    permissions:
      contents: read # For checkout a private repository
      pull-requests: write # For ci-info and github-comment
    outputs:
      targets: ${{ steps.list-targets.outputs.targets }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.59.0

      - uses: suzuki-shunsuke/tfaction@e73362800a67d5f85079894929acf7251cf5dbea # v2.0.0-9
        id: list-targets
        with:
          action: list-targets

  apply:
    timeout-minutes: 30
    name: "apply (${{matrix.target.target}})"
    runs-on: ${{matrix.target.runs_on}}
    needs: setup
    # if services is empty, the build job is skipped
    if: "join(fromJSON(needs.setup.outputs.targets), '') != ''"
    strategy:
      fail-fast: false
      matrix:
        target: ${{fromJSON(needs.setup.outputs.targets)}}
    env:
      TFACTION_TARGET: ${{matrix.target.target}}
      TFACTION_WORKING_DIR: ${{matrix.target.working_directory}}
      TFACTION_JOB_TYPE: ${{matrix.target.job_type}}
      TFACTION_SKIP_TERRAFORM: "${{matrix.target.skip_terraform}}"
    permissions:
      id-token: write # For OIDC
      contents: read # To checkout a private repository
      issues: write # For drift detection
      actions: "read" # To download plan files from GitHub Artifacts
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.59.0

      - name: Set up git to checkout private Terraform Modules
        run: gh auth setup-git
        # CHECK: This is required to download private modules in `terraform init` via HTTPS
        # You can remove this step if you don't use private modules
        env:
          GH_HOST: github.com

      - name: Get or create a drift issue
        uses: suzuki-shunsuke/tfaction@e73362800a67d5f85079894929acf7251cf5dbea # v2.0.0-9
        # CHECK: You can remove this step if you don't use drift detection
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
        with:
          action: get-or-create-drift-issue
          # issues:write - create a drift issue

      - name: Set up
        uses: suzuki-shunsuke/tfaction@e73362800a67d5f85079894929acf7251cf5dbea # v2.0.0-9
        id: setup
        with:
          action: setup

      - name: terraform init
        uses: suzuki-shunsuke/tfaction@e73362800a67d5f85079894929acf7251cf5dbea # v2.0.0-9
        with:
          action: terraform-init

      - name: Apply
        id: apply
        uses: suzuki-shunsuke/tfaction@e73362800a67d5f85079894929acf7251cf5dbea # v2.0.0-9
        with:
          # pull-requests:write # Post comments on the PR
          action: apply

      - name: Generate token
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/follow-up-pr
        id: token
        if: failure()
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write # Push commits
          permission-pull-requests: write # Create a pull request

      - name: Update related PR branches
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/update-pr-branch
        uses: suzuki-shunsuke/tfaction@e73362800a67d5f85079894929acf7251cf5dbea # v2.0.0-9
        if: always()
        with:
          action: update-pr-branch
          # pull-requests:write
          # contents:write
          github_token: ${{ steps.token.outputs.token }}

      - name: Create follow up PR
        if: failure()
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/follow-up-pr
        uses: suzuki-shunsuke/tfaction@e73362800a67d5f85079894929acf7251cf5dbea # v2.0.0-9
        with:
          action: create-follow-up-pr
          # pull-requests:write
          # contents:write
          github_token: ${{steps.token.outputs.token}}

      - name: Update a drift issue
        if: always()
        # CHECK: You can remove this step if you don't use drift detection
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
        uses: suzuki-shunsuke/tfaction@e73362800a67d5f85079894929acf7251cf5dbea # v2.0.0-9
        with:
          action: update-drift-issue
          status: ${{job.status}}
          # issues:write
