---
# This workflow is optional
# https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/terraform-plan-generate-config-out
name: Generate code by terraform plan -generate-config-out
run-name: Generate code by terraform plan -generate-config-out (${{inputs.working_dir}})
on:
  workflow_dispatch:
    inputs:
      working_dir:
        description: working directory
        required: true
      file:
        description: file name
        required: true
      branch:
        description: branch name
        required: true

env:
  TFACTION_WORKING_DIR: ${{github.event.inputs.working_dir}}
  TFACTION_JOB_TYPE: terraform
  FILE: ${{inputs.file}}
  BRANCH: ${{inputs.branch}}
jobs:
  import:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: write # For OIDC
      contents: read # For checkout a private repository
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{inputs.branch}}
          persist-credentials: false

      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.60.1
          working_directory: ${{env.TFACTION_WORKING_DIR}}
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - name: Generate a GitHub access token
        id: token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write # Push commits

      - name: Set up
        uses: suzuki-shunsuke/tfaction@0627b0a1dfec9479a3fa73a5831be7979661b7eb # v2.0.4
        id: setup
        with:
          action: setup
          github_token: ${{steps.token.outputs.token}}

      - name: terraform init
        uses: suzuki-shunsuke/tfaction@0627b0a1dfec9479a3fa73a5831be7979661b7eb # v2.0.4
        with:
          action: terraform-init
          github_token: ${{steps.token.outputs.token}}

      - name: Generate and push generated code by terraform plan -generate-config-out
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/terraform-plan-generate-config-out
        uses: suzuki-shunsuke/tfaction@0627b0a1dfec9479a3fa73a5831be7979661b7eb # v2.0.4
        with:
          action: generate-config-out
          # contents: write - push a commit
          github_token: ${{steps.token.outputs.token}}
          branch: ${{inputs.branch}}
          file: ${{inputs.file}}
