---
# This workflow is optional
# https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/terraform-plan-generate-config-out
name: Generate code by terraform plan -generate-config-out
run-name: Generate code by terraform plan -generate-config-out (${{inputs.working_dir}})
on:
  workflow_dispatch:
    inputs:
      working_dir:
        description: working directory
        required: true
      file:
        description: file name
        required: true
      branch:
        description: branch name
        required: true

env:
  TFACTION_WORKING_DIR: ${{github.event.inputs.working_dir}}
  TFACTION_JOB_TYPE: terraform
  FILE: ${{inputs.file}}
  BRANCH: ${{inputs.branch}}
jobs:
  import:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      id-token: write # For OIDC
      contents: read # For checkout a private repository
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{inputs.branch}}
          persist-credentials: false

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.59.0
          working_directory: ${{env.TFACTION_WORKING_DIR}}
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - name: Generate a GitHub access token
        id: token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write # Push commits

      - name: Set up
        uses: suzuki-shunsuke/tfaction@e73362800a67d5f85079894929acf7251cf5dbea # v2.0.0-9
        id: setup
        with:
          action: setup
          github_token: ${{steps.token.outputs.token}}

      - name: terraform init
        uses: suzuki-shunsuke/tfaction@e73362800a67d5f85079894929acf7251cf5dbea # v2.0.0-9
        with:
          action: terraform-init
          github_token: ${{steps.token.outputs.token}}

      - name: Generate and push generated code by terraform plan -generate-config-out
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/terraform-plan-generate-config-out
        uses: suzuki-shunsuke/tfaction@e73362800a67d5f85079894929acf7251cf5dbea # v2.0.0-9
        with:
          action: generate-config-out
          # contents: write - push a commit
          github_token: ${{steps.token.outputs.token}}
          branch: ${{inputs.branch}}
          file: ${{inputs.file}}
