---
# This workflow is optional
# https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/module
name: Release a Terraform Module
run-name: Release a Terraform Module (${{inputs.module_path}} ${{inputs.version}})
on:
  workflow_dispatch:
    inputs:
      module_path:
        description: "Module path"
        required: true
      version:
        description: "Module version"
        required: true
env:
  TFACTION_TARGET: ${{github.event.inputs.module_path}}
jobs:
  release-module:
    timeout-minutes: 10
    name: "release-module (${{github.event.inputs.module_path}})"
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To create a release
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.60.1

      - uses: suzuki-shunsuke/tfaction@0627b0a1dfec9479a3fa73a5831be7979661b7eb # v2.0.4
        with:
          action: release-module
          version: ${{ github.event.inputs.version }}
          module_path: ${{ github.event.inputs.module_path }}
