---
# This workflow is optional
# https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/module
name: Release a Terraform Module
run-name: Release a Terraform Module (${{inputs.module_path}} ${{inputs.version}})
on:
  workflow_dispatch:
    inputs:
      module_path:
        description: "Module path"
        required: true
      version:
        description: "Module version"
        required: true
env:
  TFACTION_TARGET: ${{github.event.inputs.module_path}}
jobs:
  release-module:
    timeout-minutes: 10
    name: "release-module (${{github.event.inputs.module_path}})"
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To create a release
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.62.3

      - uses: suzuki-shunsuke/tfaction@f62d11ce89de2aa26b00efaa266e449769f70442 # v2.1.0
        with:
          action: release-module
          version: ${{ github.event.inputs.version }}
          module_path: ${{ github.event.inputs.module_path }}
