---
# This workflow is optional
# https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/module
name: Release a Terraform Module
run-name: Release a Terraform Module (${{inputs.module_path}} ${{inputs.version}})
on:
  workflow_dispatch:
    inputs:
      module_path:
        description: "Module path"
        required: true
      version:
        description: "Module version"
        required: true
env:
  TFACTION_TARGET: ${{github.event.inputs.module_path}}
jobs:
  release-module:
    timeout-minutes: 10
    name: "release-module (${{github.event.inputs.module_path}})"
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To create a release
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.59.0

      - uses: suzuki-shunsuke/tfaction@f24a40308c268d6597a72eab8da2edf9cc87da1d # v2.0.0-8
        with:
          action: release-module
          version: ${{ github.event.inputs.version }}
          module_path: ${{ github.event.inputs.module_path }}
