# This workflow is optional.
name: Detect drift
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # hourly
    - cron: "0 * * * *"
jobs:
  pick-out-drift-issues:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write # To close issues
    outputs:
      issues: ${{steps.pick-out-drift-issues.outputs.issues}}
      has_issues: ${{steps.pick-out-drift-issues.outputs.has_issues}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.59.0
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - uses: suzuki-shunsuke/tfaction@f24a40308c268d6597a72eab8da2edf9cc87da1d # v2.0.0-8
        id: pick-out-drift-issues
        with:
          action: pick-out-drift-issues
          github_token: ${{github.token}}

  detect-drift:
    timeout-minutes: 30
    name: "detect-drift (${{matrix.issue.target}})"
    runs-on: ${{matrix.issue.runs_on}}
    needs: pick-out-drift-issues
    permissions:
      issues: write # For github-comment and tfcmt
      contents: write # To push commits
      id-token: write # For OIDC
    if: fromJSON(needs.pick-out-drift-issues.outputs.has_issues)
    strategy:
      fail-fast: false
      matrix:
        issue: ${{fromJSON(needs.pick-out-drift-issues.outputs.issues)}}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
          # issues:write - Create and update issues
          permissions: >-
            {
              "issues": "write"
            }
          # issues of Drift Detection
          repositories: >-
            [
              "tfaction-example"
            ]

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.59.0
        env:
          GITHUB_TOKEN: ${{github.token}}

      - uses: suzuki-shunsuke/tfaction@f24a40308c268d6597a72eab8da2edf9cc87da1d # v2.0.0-8
        with:
          action: set-drift-env
          issue: ${{toJSON(matrix.issue)}}

      - uses: suzuki-shunsuke/tfaction@f24a40308c268d6597a72eab8da2edf9cc87da1d # v2.0.0-8
        id: setup
        with:
          action: setup
          github_token: ${{steps.generate_token.outputs.token}}
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

      - name: terraform init
        uses: suzuki-shunsuke/tfaction@f24a40308c268d6597a72eab8da2edf9cc87da1d # v2.0.0-8
        with:
          action: terraform-init
          github_token: ${{steps.generate_token.outputs.token}}
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

      - uses: suzuki-shunsuke/tfaction@f24a40308c268d6597a72eab8da2edf9cc87da1d # v2.0.0-8
        with:
          action: test
          github_token: ${{steps.generate_token.outputs.token}}
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

      - uses: suzuki-shunsuke/tfaction@f24a40308c268d6597a72eab8da2edf9cc87da1d # v2.0.0-8
        with:
          action: plan
          github_token: ${{steps.generate_token.outputs.token}}
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}

      - uses: suzuki-shunsuke/tfaction@f24a40308c268d6597a72eab8da2edf9cc87da1d # v2.0.0-8
        if: always()
        with:
          action: update-drift-issue
          status: ${{job.status}}
          github_token: ${{steps.generate_token.outputs.token}}
