# This workflow is optional.
# https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
name: Create drift issues
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # daily
    - cron: "0 0 * * *"
jobs:
  create-drift-issues:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.62.3

      - uses: suzuki-shunsuke/tfaction@d0d52eb8b2ff13d6e27ac9653d038df384e58827 # v2.0.5
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
        with:
          # issues:write
          action: create-drift-issues
