# This workflow is optional.
# https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
name: Create drift issues
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # daily
    - cron: "0 0 * * *"
jobs:
  create-drift-issues:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.59.1

      - uses: suzuki-shunsuke/tfaction@e73362800a67d5f85079894929acf7251cf5dbea # v2.0.0-9
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
        with:
          # issues:write
          action: create-drift-issues
