# This workflow is optional.
# https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
name: Detect drift
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # hourly
    - cron: "0 * * * *"
jobs:
  pick-out-drift-issues:
    timeout-minutes: 10
    runs-on: ubuntu-slim
    permissions:
      contents: read
      issues: write # To close issues
    outputs:
      issues: ${{steps.pick-out-drift-issues.outputs.issues}}
      has_issues: ${{steps.pick-out-drift-issues.outputs.has_issues}}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.60.1
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
        id: pick-out-drift-issues
        with:
          action: pick-out-drift-issues
          github_token: ${{github.token}}

  detect-drift:
    timeout-minutes: 30
    name: "detect-drift (${{matrix.issue.target}})"
    runs-on: ${{matrix.issue.runs_on}}
    needs: pick-out-drift-issues
    permissions:
      issues: write # For github-comment and tfcmt
      contents: write # To push commits
      id-token: write # For OIDC
    if: fromJSON(needs.pick-out-drift-issues.outputs.has_issues)
    strategy:
      fail-fast: false
      matrix:
        issue: ${{fromJSON(needs.pick-out-drift-issues.outputs.issues)}}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.60.1
        env:
          GITHUB_TOKEN: ${{github.token}}

      - uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
        with:
          action: set-drift-env
          issue: ${{toJSON(matrix.issue)}}

      - uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        id: setup
        with:
          action: setup

      - name: terraform init
        uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        with:
          action: terraform-init

      - uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        with:
          action: test

      - uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        with:
          action: plan

      - uses: suzuki-shunsuke/tfaction@45bd9d6d7f1c396b5f1ca6f4d31dd8247e812539 # v2.0.3
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
        if: always()
        with:
          action: update-drift-issue
          status: ${{job.status}}
