# This workflow is optional.
# https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
name: Synchronize drift issue description

on:
  issue_comment:
    types:
      - created

jobs:
  sync-issue:
    timeout-minutes: 10
    runs-on: ubuntu-slim
    # CHECK: PLEASE CHANGE github.actor
    if: |
      !github.event.issue.pull_request &&
      startsWith(github.event.issue.title, 'Terraform Drift (') && endsWith(github.event.issue.title, ')') &&
      github.actor == 'suzuki-shunsuke'
    permissions:
      issues: write
    steps:
      - uses: suzuki-shunsuke/tfaction@6ad59de70ee7e9c0a11c665c4439b5c148c74328 # v2.0.1
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
        with:
          action: sync-drift-issue-description
