# This workflow is optional.
# https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
name: Synchronize drift issue description

on:
  issue_comment:
    types:
      - created

jobs:
  sync-issue:
    timeout-minutes: 10
    runs-on: ubuntu-slim
    # CHECK: PLEASE CHANGE github.actor
    if: |
      !github.event.issue.pull_request &&
      startsWith(github.event.issue.title, 'Terraform Drift (') && endsWith(github.event.issue.title, ')') &&
      github.actor == 'suzuki-shunsuke'
    permissions:
      issues: write
    steps:
      - uses: suzuki-shunsuke/tfaction@9fdf06dabe8e3d9acb003939af57e477a0d3090e # v2.2.0
        # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/drift-detection
        with:
          action: sync-drift-issue-description
