---
name: pull_request
on: pull_request
concurrency:
  group: ${{ github.workflow }}--${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  status-check:
    runs-on: ubuntu-slim
    if: always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
    timeout-minutes: 10
    permissions: {}
    needs:
      - test
    steps:
      - run: exit 1
  test:
    uses: ./.github/workflows/workflow_call_test.yaml
    secrets:
      APP_PRIVATE_KEY: ${{secrets.APP_PRIVATE_KEY}}
    permissions:
      contents: read
      pull-requests: write
      id-token: write
