---
# This workflow is optional.
name: conftest verify
on: workflow_call
jobs:
  conftest-verify:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install conftest and github-comment
        uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.59.1

      - name: conftest verify
        run: github-comment exec -- conftest verify --no-color -p policy/terraform
        env:
          GITHUB_TOKEN: ${{github.token}}
