---
name: update-aqua-checksums
on:
  workflow_call:
    secrets:
      APP_PRIVATE_KEY:
        required: true
jobs:
  update-aqua-checksums:
    # Update aqua-checksums.json and push a commit
    uses: aquaproj/update-checksum-workflow/.github/workflows/update-checksum.yaml@eba908314cdc3b2ab7fb7546950c05a666effbc0 # v1.0.5
    permissions:
      contents: read
    with:
      aqua_version: v2.59.1
      prune: true
    secrets:
      gh_app_id: ${{vars.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
