---
# This workflow is optional.
name: conftest verify
on: workflow_call
jobs:
  conftest-verify:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install conftest and github-comment
        uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.62.2

      - name: conftest verify
        run: github-comment exec -- conftest verify --no-color -p policy/terraform
        env:
          GITHUB_TOKEN: ${{github.token}}
