---
name: plan
on:
  workflow_call:
    inputs:
      targets:
        required: true
        type: string
    secrets:
      APP_PRIVATE_KEY:
        required: true

jobs:
  plan:
    timeout-minutes: 30
    name: "plan (${{matrix.target.target}})"
    runs-on: ${{matrix.target.runs_on}}
    permissions:
      id-token: write # For OIDC. https://docs.github.com/en/actions/concepts/security/openid-connect
      contents: read # To checkout private repositories
    env:
      TFACTION_TARGET: ${{matrix.target.target}}
      TFACTION_WORKING_DIR: ${{matrix.target.working_directory}}
      TFACTION_JOB_TYPE: ${{matrix.target.job_type}}
      TFACTION_SKIP_TERRAFORM: "${{matrix.target.skip_terraform}}"
    strategy:
      fail-fast: false
      matrix:
        target: ${{fromJSON(inputs.targets)}}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.60.1

      - name: Create a GitHub App installation access token
        id: token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write # Push commits
          permission-pull-requests: write # Create PR comments and labels

      - name: Set up
        uses: suzuki-shunsuke/tfaction@0627b0a1dfec9479a3fa73a5831be7979661b7eb # v2.0.4
        with:
          action: setup
          github_token: ${{steps.token.outputs.token}}

      - name: terraform init
        uses: suzuki-shunsuke/tfaction@0627b0a1dfec9479a3fa73a5831be7979661b7eb # v2.0.4
        with:
          action: terraform-init
          github_token: ${{steps.token.outputs.token}}

      - name: Test
        uses: suzuki-shunsuke/tfaction@0627b0a1dfec9479a3fa73a5831be7979661b7eb # v2.0.4
        with:
          action: test
          github_token: ${{steps.token.outputs.token}}

      - name: Plan
        uses: suzuki-shunsuke/tfaction@0627b0a1dfec9479a3fa73a5831be7979661b7eb # v2.0.4
        with:
          action: plan
          github_token: ${{steps.token.outputs.token}}
        env:
          TF_CLI_ARGS_plan: "-parallelism=30" # https://suzuki-shunsuke.github.io/tfaction/docs/unreleased/terraform-options
