---
name: test (workflow_call)
on:
  workflow_call:
    secrets:
      APP_PRIVATE_KEY:
        required: true
permissions: {}
jobs:
  paths-filter:
    uses: ./.github/workflows/workflow_call_paths_filter.yaml
    permissions:
      contents: read
      pull-requests: read

  conftest-verify:
    uses: ./.github/workflows/workflow_call_conftest_verify.yaml
    needs: paths-filter
    if: needs.paths-filter.outputs.conftest-verify == 'true'
    permissions:
      contents: read
      pull-requests: write

  opa-fmt:
    uses: ./.github/workflows/workflow_call_opa_fmt.yaml
    needs: paths-filter
    if: needs.paths-filter.outputs.opa-fmt == 'true'
    permissions:
      contents: read
      pull-requests: write
    secrets:
      APP_PRIVATE_KEY: ${{secrets.APP_PRIVATE_KEY}}

  renovate-config-validator:
    uses: ./.github/workflows/workflow_call_renovate_config_validator.yaml
    needs: paths-filter
    if: needs.paths-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  list_and_plan:
    uses: ./.github/workflows/workflow_call_list_and_plan.yaml
    needs: paths-filter
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    secrets:
      APP_PRIVATE_KEY: ${{secrets.APP_PRIVATE_KEY}}

  update-aqua-checksums:
    uses: ./.github/workflows/workflow_call_update_aqua_checksums.yaml
    needs: paths-filter
    if: needs.paths-filter.outputs.update-aqua-checksums == 'true'
    permissions:
      contents: read
    secrets:
      APP_PRIVATE_KEY: ${{secrets.APP_PRIVATE_KEY}}
