---
name: update-aqua-checksums
on:
  workflow_call:
    secrets:
      APP_PRIVATE_KEY:
        required: false
jobs:
  update-aqua-checksums:
    # Update aqua-checksums.json and push a commit
    uses: aquaproj/update-checksum-workflow/.github/workflows/update-checksum.yaml@d248abb88efce715d50eb324100d9b29a20f7d18 # v1.0.4
    permissions:
      contents: read
    with:
      aqua_version: v2.59.0
      prune: true
    secrets:
      gh_app_id: ${{vars.APP_ID}}
      APP_PRIVATE_KEY: ${{secrets.APP_PRIVATE_KEY}}
